#define MASTER_LEFT

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 180

#define ONESHOT_TIMEOUT 1000
#define ONESHOT_TAP_TOGGLE 9999

#define COMBO_MUST_PRESS_IN_ORDER
#define COMBO_TERM_PER_COMBO
#define COMBO_TERM 100
