#define MASTER_LEFT

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 180

#define ONESHOT_TIMEOUT 1000
#define ONESHOT_TAP_TOGGLE 9999

#define COMBO_MUST_PRESS_IN_ORDER
#define COMBO_TERM_PER_COMBO
#define COMBO_TERM 100

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_LEFT
#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 150
